 server {
      listen [::]:443 ssl;
      listen 443 ssl;

      server_name sandbox.elearning.reb.rw www.sandbox.elearning.reb.rw;

      # SSL - managed by Certbot
      ssl_certificate /etc/letsencrypt/live/elearning.reb.rw/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/elearning.reb.rw/privkey.pem;
      include /etc/letsencrypt/options-ssl-nginx.conf;
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

      # Logs
      access_log off;
      error_log /var/log/nginx/sandbox.elearning.reb.rw.br-error.log warn;

      include snippets/security.conf;

      # Reverse proxy to Moodle backend
      location / {
          proxy_pass http://10.10.68.202:80;
          proxy_http_version 1.1;

          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;

          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          proxy_connect_timeout 60s;
          proxy_send_timeout 6000s;
          proxy_read_timeout 6000s;

          proxy_buffering on;
          proxy_buffer_size 128k;
          proxy_buffers 4 256k;
          proxy_busy_buffers_size 256k;

          client_max_body_size 512M;
      }

      include snippets/moodle-security.conf;
  }

  server {
      if ($host = www.sandbox.elearning.reb.rw) {
          return 301 https://$host$request_uri;
      } # managed by Certbot
      if ($host = sandbox.elearning.reb.rw) {
          return 301 https://$host$request_uri;
      } # managed by Certbot

      listen 80;
      listen [::]:80;

      server_name sandbox.elearning.reb.rw www.sandbox.elearning.reb.rw;

      # Let's Encrypt ACME challenge
      location ^~ /.well-known/acme-challenge/ {
          default_type "text/plain";
          root /var/www/sandbox.elearning.reb.rw/moodle;
          allow all;
      }

      return 404; # managed by Certbot
  }

